version: 2
updates:
  # Dependencies for Maven
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'daily'

  # Dependencies for Gradle
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'daily'

  # Dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
