micronaut:
  application:
    name: app
  security:
    authentication: idtoken
    oauth2:
      clients:
        okta:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          openid:
            issuer: ${ISSUER}
    endpoints:
      logout:
        get-allowed: true
    token:
      jwt:
        claims-validators:
          issuer: ${ISSUER}
        signatures:
          jwks:
            okta:
              url: ${ISSUER}/v1/keys
