micronaut:
  application:
    name: app
  security:
    authentication: idtoken
    oauth2:
      clients:
        okta:
          scopes: ['openid', 'profile', 'email', 'offline_access']
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          openid:
            issuer: ${ISSUER}
    endpoints:
      logout:
        get-allowed: true
