name: Micronaut CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Use Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          java-package: jdk
      - name: Create .env file
        uses: DamianReeves/write-file-action@1
        with:
          path: ${{ env.GITHUB_WORKSPACE }}/.okta.env
          contents: |
            echo "export ISSUER=${{ secrets.ISSUER }}"
            echo "export CLIENT_ID=${{ secrets.CLIENT_ID }}"
            echo "export CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}"
          write-mode: overwrite
      - name: Build and test
        run: |
          cat .okta.env
          source .okta.env
          mvn -B -ntp verify
